theme: jekyll-theme-cayman
title: Fractional Distillation of Tech!
description: Large-Scale Computing, Emerging Programming Paradigms and Big Data Software Abstractions, Parallel Programming, Distributed Systems, Cloud Computing, Productivity Enhancing Tools and Tips. Ever pondered this question: "Why so many technologies out there? Can someone distill these to high-level concepts and implementation?". Sounds interesting? If Yes: "I'm your pilot, fasten your seatbelts and lets take-off! And don't doze off as soon we're going to have a bird's eye view!"
future: true
