theme: jekyll-theme-cayman
title: Fractional Distillation of Tech!
description: Large-Scale Computing, Emerging Programming Paradigms and Abstractions by Big Data Frameworks, Parallel Programming, Distributed Systems, Cloud Computing, Productivity Enhancing Tools and Tips, Data Science.
