theme: jekyll-theme-cayman
title: Steering Golden Chariot on the Tech!
description: Articles about state-of-the-art emerging technologies and concepts in the computer science domain with special focus on solutions to data intensive problems. It also has humor, quotations sections.
